---
- name: 安装原厂灯光与音频服务组件
  command: "opkg install lumimqtt lumimqttd"
  register: opkg_lumi
  changed_when: "'Configuring' in opkg_lumi.stdout"

- name: 引入 lumimqtt 相关的配置与重启任务
  ansible.builtin.include_tasks: lumimqtt.yml

- name: 引入 lumimqttd 相关的音频及 MQTT 清理任务
  ansible.builtin.include_tasks: lumimqttd.yml
