---
wireless_radio_path: 'platform/soc/2100000.bus/2190000.mmc/mmc_host/mmc0/mmc0:0001/mmc0:0001:1'
wireless_radio_band: '2g'
wireless_radio_channel: 'auto'
wireless_radio_htmode: 'NOHT'

wireless_iface_name: 'router_client'
wireless_iface_device: 'radio0'
wireless_iface_network: 'wan'
wireless_iface_mode: 'sta'
wireless_ssid: 'Home-IoT'
wireless_encryption: 'psk2'
wireless_key: '&t8hA$*i'

wireless_radio1_path: 'platform/soc/2100000.bus/2190000.mmc/mmc_host/mmc0/mmc0:0001/mmc0:0001:1+1'
wireless_radio1_band: '2g'
wireless_radio1_channel: '1'
wireless_radio1_htmode: 'NOHT'
wireless_radio1_disabled: '1'

wireless_iface1_name: 'default_radio1'
wireless_iface1_device: 'radio1'
wireless_iface1_network: 'lan'
wireless_iface1_mode: 'ap'
wireless_iface1_ssid: 'OpenWrt'
wireless_iface1_encryption: 'none'
