all:
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: "uHqZ3P9k"  # 临时使用默认Root密码
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    floor1_hub:
      ansible_host: 192.168.50.234
      hub_name: "Lumi Router Floor 1"
      squeezelite_name: "SqueezeWrt_F1"
    floor2_hub:
      ansible_host: 192.168.50.151
      hub_name: "Lumi Router Floor 2"
      squeezelite_name: "SqueezeWrt_F2"
