all:
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: "*8^6#3Ab"
    ansible_port: 22
  hosts:
    floor1_hub:
      ansible_host: 192.168.50.101
      hub_name: "Lumi Router Floor 1"
      squeezelite_name: "Squeezelite_Lumi_F1"
      hub_mac: "7c49eb924bd7"
    floor2_hub:
      ansible_host: 192.168.50.201
      hub_name: "Lumi Router Floor 2"
      squeezelite_name: "Squeezelite_Lumi_F2"
      hub_mac: "7c49eb93b068"
